name: ci
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"

      - uses: pnpm/action-setup@v2

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Run prettier
        run: pnpm format:check

      - name: Run eslint
        run: pnpm lint
