name: ci
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"

      - name: Run prettier
        run: yarn format:check

      - name: Run eslint
        run: yarn lint
