name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"

      - uses: pnpm/action-setup@v2.2.2

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Build
        run: |
          pnpm build

      - name: Create zip file
        run: zip -r dist.zip ./dist

      - name: Upload zip file
        uses: softprops/action-gh-release@v1
        with:
          files: dist.zip
